nl(tutorial): translates index
gatsbyjs/gatsby-nl pull request #5
Opened 2019-10-29 13:47 UTC by joranquinten

2019-10-29 17:03 UTC, MichaelDeBoey requested changes

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +Ga verder met [extra Gatsby-tutorials](/tutorial/extra-tutorials/).
Links shouldn't change

```suggestion
Ga verder met [extra Gatsby-tutorials](/tutorial/additional-tutorials/).
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +Meer informatie over het gebruik en het bouwen van thema's met de [Gatsby-thema-tutorials](/tutorial/theme-tutorials/).
```suggestion
Meer informatie over het gebruik en het bouwen van thema's met de [Gatsby-thema tutorials](/tutorial/theme-tutorials/).
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +1. [Inleiding tot het gebruik van CSS in Gatsby](/tutorial/part-two /): verken bibliotheken zoals Typography.js en CSS-modules.
Links shouldn't change

```suggestion
1. [Inleiding tot het gebruik van CSS in Gatsby](/tutorial/part-two/): verken bibliotheken zoals Typography.js en CSS-modules.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +Gatsby-thema's abstraheren al je standaardconfiguraties (gedeelde functionaliteit, gegevensbron, ontwerp) van je site naar een installeerbaar pakket.
```suggestion
Gatsby-thema's abstraheren al je standaardconfiguraties (gedeelde functionaliteit, gegevensbronnen, ontwerp) van je site naar een installeerbaar pakket.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +0. [Stel je ontwikkelomgeving in](/tutorial/part-zero/): we laten je kennismaken met basistechnologieën die Gatsby aansturen en begeleiden je bij het opzetten van je ontwikkelomgeving.
```suggestion
0. [Stel je ontwikkelomgeving in](/tutorial/part-zero/): We laten je kennismaken met basistechnologieën die Gatsby aansturen en begeleiden je bij het opzetten van je ontwikkelomgeving.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +1. [Maak kennis met Gatsby-bouwstenen](/tutorial/part-one/): nieuwe projecten starten, sites ontwikkelen en implementeren.
```suggestion
1. [Maak kennis met Gatsby-bouwstenen](/tutorial/part-one/): Nieuwe projecten starten, sites ontwikkelen en implementeren.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +1. [Geneste lay-outs bouwen in Gatsby](/tutorial/part-three/): lay-outs zijn delen van je site die worden hergebruikt op meerdere pagina's, zoals bijvoorbeeld kop- en voetteksten.
```suggestion
1. [Geneste lay-outs bouwen in Gatsby](/tutorial/part-three/): Lay-outs zijn delen van je site die worden hergebruikt op meerdere pagina's, zoals bijvoorbeeld kop- en voetteksten.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +4. [Gegevens opvragen in een blog](/tutorial/part-four/): maak een blog en gebruik een GraphQL-query om de titel van uw site in de kop van de blog te plaatsen.
```suggestion
4. [Gegevens opvragen in een blog](/tutorial/part-four/): Maak een blog en gebruik een GraphQL-query om de titel van uw site in de kop van de blog te plaatsen.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +5. [Bron plugins en gevraagde gegevens weergeven](/tutorial/part-five /): gebruik een bron plugin om Markdown-blogberichten naar uw site te halen en een indexpagina met een lijst met blogberichten te
```suggestion
5. [Bron-plugins en gevraagde gegevens weergeven](/tutorial/part-five/): gebruik een bron-plugin om Markdown-blogberichten naar uw site te halen en een indexpagina met een lijst met blogberichten te maken.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +6. [Transformator plug-ins](/tutorial/part-six/): gebruik een transformator-plugin om uw Markdown-blogberichten te transformeren naar een vorm die de blog kan weergeven.
```suggestion
6. [Transformator plug-ins](/tutorial/part-six/): gebruik een transformator-plugin om uw Markdown blogberichten te transformeren naar een vorm die de blog kan weergeven.
```

2019-10-29 17:03 UTC, MichaelDeBoey commented on docs/tutorial/index.md
> +8. [Een site voorbereiden voor livegang](/tutorial/part-eight/): leer hoe je je site kunt controleren op prestaties en aanbevolden richtlijnen voor toegankelijkheid, SEO en meer.
```suggestion
8. [Een site voorbereiden voor livegang](/tutorial/part-eight/): Leer hoe je je site kunt controleren op prestaties en aanbevolen richtlijnen voor toegankelijkheid, SEO en meer.
```

2019-10-29 21:03 UTC, joranquinten commented
You could've rejected this entirely, sorry for this one, I don't think it's up to date. I'll double check my PRs from now on

2019-10-30 08:17 UTC, joranquinten commented
Rechecked the spelling and file and applied the capitalization rule after the : consistently now.

2019-11-07 18:42 UTC, joranquinten commented
@MichaelDeBoey Can you check this one out?

2019-11-12 12:59 UTC, joranquinten commented
I think every issue has been resolved, or the interface is hiding stuff from me 🤷‍♂️

2020-01-05 10:05 UTC, 0x80 requested changes
Great work on translating!

2020-01-05 10:05 UTC, 0x80 commented on docs/tutorial/index.md
> +> De volledige tutorial is bedoeld om zo toegankelijk mogelijk te zijn voor mensen zonder veel ervaring met webontwikkeling (nog niet!) - je hoeft geen expert te zijn. Als je liever rechtstreeks naar
voor mensen die (nog) niet veel ervaring hebben met webontwikkeling - je hoeft geen ...

2020-01-05 10:05 UTC, 0x80 commented on docs/tutorial/index.md
> +In deze tutorials leer je hoe je met GraphQL gegevens van vrijwel overal naar uw Gatsby-site kunt halen.
I'd suggest "met GraphQL data van willekeurige bronnen in jouw Gatsby-site kunt gebruiken".

Use of "uw" doesn't make sense if you're addressing the user with "je" all the time. Data is also a Dutch word and I think is clearer.

2020-01-05 10:05 UTC, 0x80 commented on docs/tutorial/index.md
> +4. [Gegevens opvragen in een blog](/tutorial/part-four/): Maak een blog en gebruik een GraphQL-query om de titel van uw site in de kop van de blog te plaatsen.
Same here. I'd use "data", because "gegevens" has a slightly different meaning to me. It is often associated with personal and private data.

2020-01-05 10:05 UTC, 0x80 commented on docs/tutorial/index.md
> +4. [Gegevens opvragen in een blog](/tutorial/part-four/): Maak een blog en gebruik een GraphQL-query om de titel van uw site in de kop van de blog te plaatsen.
This comment applies to any use of the word "gegevens" in every translation, so I will not repeat myself.

2020-01-05 10:05 UTC, 0x80 commented on docs/tutorial/index.md
> +Er zijn veel gebruiksscenario's voor Gatsby, waarvan sommige niet worden behandeld in de eerste set tutorials om je tijdens het leren niet te overspoelen. Het gedeelte Aanvullende tutorials van Gatsb
Aanvullende Tutorials

2025-01-20 16:37 UTC, closed without merging